### ISSUE TITLE
Ошибка Trying to get property of non-object

### ISSUE THREAD

**Issue by qwermus** [fr05t1k/esia#20]
Спасибо за модуль авторизации в ЕСИА. Однако у меня возникли проблемы при получении профиля пользователя.
Авторизация прошла успешно, вернулся на redirectUrl . Попытался выполнить следующий код:

```
    $esia->getToken($_GET['code']);
    $personInfo = $esia->getPersonInfo();
    var_dump($personInfo);
```

Однако получил следующее:

```
Notice: Trying to get property of non-object in /var/www/html/includes/Esia/vendor/fr05t1k/esia/src/OpenId.php on line 171

Notice: Undefined offset: 1 in /var/www/html/includes/Esia/vendor/fr05t1k/esia/src/OpenId.php on line 175

Notice: Trying to get property of non-object in /var/www/html/includes/Esia/vendor/fr05t1k/esia/src/OpenId.php on line 176

Fatal error: Uncaught exception 'esia\exceptions\RequestFailException' with message 'Token is empty. Please set the token before' in /var/www/html/includes/Esia/vendor/fr05t1k/esia/src/OpenId.php:346
Stack trace:
#0 /var/www/html/includes/Esia/vendor/fr05t1k/esia/src/OpenId.php(264): esia\OpenId->buildRequest()
#1 /var/www/html/test.php(25): esia\OpenId->getPersonInfo()
#2 {main}
  thrown in /var/www/html/includes/Esia/vendor/fr05t1k/esia/src/OpenId.php on line 346
```

Пытался разобраться сам, но не понимаю, куда копать.
Не подскажешь, в чем я ошибся?
Заранее благодарю

**Comment by qwermus** [comment]
Удивительно - задал вопрос, и через 10 минут ошибка пропала и пришли данные пользователя. Прошу прощения, что отвлек, вопрос можно считать закрытым:)

**Comment by fr05t1k** [comment]
btw если используете php7.1 можете обновиться до версии 2.0 :)
